services:
  postgres:
    container_name: tps-postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres

  temporal:
    container_name: tps-temporal
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_SEEDS=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
    image: temporalio/auto-setup:1.21.3.0
    ports:
      - 7233:7233

  temporal-admin-tools:
    container_name: tps-temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.21.3.0

  temporal-web:
    container_name: tps-temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.16.2
    ports:
      - 8080:8080
