services:
  postgres:
    container_name: tps-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres

  temporal:
    container_name: tps-temporal
    image: temporalio/auto-setup:1.21.3.0
    restart: always
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_SEEDS=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
    ports:
      - 7233:7233

  worker:
    container_name: tps-worker
    build: ./
    restart: always
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233

  temporal-web:
    container_name: tps-temporal-web
    image: temporalio/ui:2.16.2
    restart: always
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - 8080:8080
